version: "3"
services:
  db:
    image: "postgres:13"
    user: $UID:$GID
    volumes:
      - "dbdata:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: e-comm
      POSTGRES_PASSWORD: SIMPLE_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    command: redis-server --requirepass ecommpasswd
    user: $UID:$GID
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"

volumes:
  dbdata:
  redis-data:
  redis-config:
