springdoc:
  api-docs:
    path: /api-docs
spring:
  profiles:
    active:
      dev
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.globally_quoted_identifiers: true
#      hibernate.enable_lazy_load_no_trans: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.region.factory_class: org.redisson.hibernate.RedissonRegionFactory
#      hibernate.cache.use_query_cache: false
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
e-comm:
  jwt:
    secret: comp9900-e-commerce-system-spring-backend-jwt-secret-8h97g09dWnv6f143BD