spring:
  datasource:
    url: "jdbc:postgresql://db:5432/e-comm"
    username: e-comm
    password: SIMPLE_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    client-type: lettuce
    url: "redis://:ecommpasswd@redis:6379"

e-comm:
  jwt:
    token-validity: 3d
    token-validity-for-remember-me: 30d
logging:
  level: warn