spring:
  datasource:
    url: "jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
  jpa:
    hibernate:
      ddl-auto: create-drop
  redis:
    port: 6300
e-comm:
  jwt:
    token-validity: 1d
    token-validity-for-remember-me: 3d
