export const GET_PRODUCTS_INFO = 'GET_PRODUCTS_INFO'
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const GET_RECOMMENDATION = 'GET_RECOMMENDATION'
export const GET_C_RECOMMENDATION = 'GET_C_RECOMMENDATION'
